#!/bin/bash

while true; do
    clear
    echo "========================================================================="
    echo "-----------------------File Management Project-------------------------"
    echo "========================================================================="
    echo "Welcome! The Main Menu is given below:"
    echo "1- List all Files and Directories"
    echo "2- Create New Files"
    echo "3- Delete Existing Files"
    echo "4- Rename Files"
    echo "5- Edit File Content"
    echo "6- Search Files"
    echo "7- Details of Particular File"
    echo "8- View Content of File"
    echo "9- Sort File Content"
    echo "10- List only Directories(Folders)"
    echo "11- List Files of Particular Extension"
    echo "12- Count Number of Directories"
    echo "13- Count Number of Files"
    echo "14- Sort Files in a Directory"
    echo "0- Exit"
    echo ""
    read -p "What action would you like to perform? (Enter 1-14 or 0 to exit): " opt1

    case $opt1 in
        1)
            echo "List all files and directories here.."
            echo "Showing all files and directories...."
            sleep 3
            echo "Loading.."
            sleep 3
            echo "-------------------------------OutPut---------------------------"
            ls
            echo ""
            ;;
        2)
            echo "Create New Files here.."
            echo "Which type of file would you like to create?"
            echo "1- .c"
            echo "2- .sh"
            echo "3- .txt"
            read -p "Enter your choice from 1-3: " filechoice

            case $filechoice in
                1)
                    read -p "Enter File Name without .c Extension: " filename
                    touch "$filename.c"
                    echo "-------------------------------OutPut---------------------------"
                    echo "File Created Successfully"
                    echo ""
                    sleep 10;
                    ;;
                2)
                    read -p "Enter File Name without .sh Extension: " filename2
                    touch "$filename2.sh"
                    echo "-------------------------------OutPut---------------------------"
                    echo "File Created Successfully"
                    echo ""
                    sleep 10;
                    ;;
                3)
                    read -p "Enter File Name without .txt Extension: " filename3
                    touch "$filename3.txt"
                    echo "-------------------------------OutPut---------------------------"
                    echo "File Created Successfully"
                    echo ""
                    sleep 10;
                    ;;
                *)
                    echo "Invalid input. Please enter a number from 1 to 3."
                    ;;
            esac
            ;;
        3)
            echo "Delete existing files here.."
            read -p "Enter the name of the file you want to delete (including extension): " delfile
            echo "-------------------------------OutPut---------------------------"

            if [ -f "$delfile" ]; then
                rm "$delfile"
                echo "Successfully Deleted."
                sleep 5;
            else
                echo "File does not exist. Try again."
            fi
            echo ""
            ;;
        4)
            echo "Rename files here.."
            read -p "Enter the old name of the file (including extension): " old
            echo "Checking for file..."
            sleep 3

            if [ -f "$old" ]; then
                echo "File exists."
                read -p "Enter the new name for the file (including extension): " new
                mv "$old" "$new"
                echo "Successfully Renamed. The file now exists with the name: $new"
            else
                echo "$old does not exist. Try again with the correct filename."
            fi
            echo ""
            ;;
        5)
            echo "Edit file content here.."
            read -p "Enter the name of the file to edit (including extension): " edit
            echo "-------------------------------OutPut---------------------------"
            echo "Checking for file..."
            sleep 3

            if [ -f "$edit" ]; then
                echo "Opening the file..."
                sleep 3
                nano "$edit"
            else
                echo "$edit does not exist. Try again."
            fi
            echo ""
            sleep 1;
            ;;
        6)
            echo "Search files here.."
            read -p "Enter the name of the file to search for (including extension): " f
            echo "-------------------------------OutPut---------------------------"

            if [ -f "$f" ]; then
                echo "Searching for $f..."
                echo "File Found."
                find /home -name "$f"
            else
                echo "File does not exist. Try again."
            fi
            echo ""
            sleep 5;
            ;;
        7)
            echo "Details of a file here.."
            read -p "Enter the name of the file to see details (including extension): " detail
            echo "-------------------------------OutPut---------------------------"
            echo "Checking for file..."
            sleep 4

            if [ -f "$detail" ]; then
                echo "Loading properties..."
                stat "$detail"
            else
                echo "$detail does not exist. Try again."
            fi
            echo ""
            ;;
        8)
            echo "View content of a file here.."
            read -p "Enter the name of the file to view (including extension): " readfile
            echo "-------------------------------OutPut---------------------------"

            if [ -f "$readfile" ]; then
                echo "Showing the content of the file..."
                sleep 3
                cat "$readfile"
            else
                echo "$readfile does not exist."
            fi
            echo ""
            sleep 10;
            ;;
        9)
            echo "Sort file content here.."
            read -p "Enter the name of the file to sort (including extension): " sortfile
            echo "-------------------------------OutPut---------------------------"

            if [ -f "$sortfile" ]; then
                echo "Sorting file content..."
                sleep 3
                sort "$sortfile"
            else
                echo "$sortfile does not exist. Try again."
            fi
            echo ""
            sleep 10;
            ;;
        10)
            echo "-------------------------------OutPut---------------------------"
            echo "List of all directories here.."
            echo "Showing all directories..."
            echo "Loading.."
            sleep 3
            ls -d */
            echo ""
            sleep 10;
            ;;
        11)
            echo "List of files with particular extensions here.."
            echo "Which type of file list would you like to see?"
            echo "1- .c"
            echo "2- .sh"
            echo "3- .txt"
            read -p "Enter your choice from 1-3: " extopt
            echo "-------------------------------OutPut---------------------------"

            case $extopt in
                1)
                    echo "List of .c files shown below."
                    echo "Loading.."
                    sleep 3
                    ls *.c
                    ;;
                2)
                    echo "List of .sh files shown below."
                    echo "Loading.."
                    sleep 3
                    ls *.sh
                    ;;
                3)
                    echo "List of .txt files shown below."
                    echo "Loading.."
                    sleep 3
                    ls *.txt
                    ;;
                *)
                    echo "Invalid input. Try again."
                    ;;
            esac
            echo ""
            sleep 10;
            ;;
        12)
            echo "-------------------------------OutPut---------------------------"
            echo "Total number of directories here.."
            echo "Loading all directories..."
            echo "Counting.."
            sleep 3
            echo "Number of directories: "
            echo $(ls -d */ | wc -w)
            echo ""
            sleep 10;
            ;;
        13)
            echo "-------------------------------OutPut---------------------------"
            echo "Total number of files in the current directory here.."
            echo "Loading all files..."
            echo "Number of files: "
            echo $(ls -l | grep -v 'total' | grep -v '^d' | wc -l)
            echo ""
            sleep 10;
            ;;
        14)
            echo "-------------------------------OutPut---------------------------"
            echo "Sort files here.."
            echo "Your request to sort files is being processed."
            echo "Sorting.."
            sleep 3
            ls | sort
            echo ""
            sleep 10;
            ;;
        0)
            echo "Goodbye!"
            exit 0
            ;;
        *)
            echo "Invalid choice. Please enter a number from 1 to 14, or 0 to exit."
            ;;
    esac
done
